### ISSUE TITLE
wa5.2 support

### ISSUE THREAD

**Issue by wakkah** [lovethiscode/Gorgeous-Whatsapp#44]
Hi, protocol wa5.2 is out, are you gonna a adapt the api?

**Comment by Whatsapp-Protocol** [comment]
This version is already supported, websocket api is already available, you can use websocket api to develop your application.

**Comment by lovethiscode** [comment]
This version is already supported, websocket api is already available, you can use websocket api to develop your application.

**Comment by wakkah** [comment]
Hi, the source code was update 5months ago, but the jni 1 month ago, I understand that the update is online in the binary form, are you gonna upload de source code?

**Comment by lovethiscode** [comment]
I won't update the source code any more. I can use rest api, which is simpler and doesn't need maintenance.






------------------ Original ------------------
From: wakkah ***@***.***&gt;
Date: Fri,Dec 3,2021 5:00 AM
To: lovethiscode/Gorgeous-Whatsapp ***@***.***&gt;
Cc: lovethiscode ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [lovethiscode/Gorgeous-Whatsapp] wa5.2 support (Issue #44)





 
Hi, the source code was update 5months ago, but the jni 1 month ago, I understand that the update is online in the binary form, are you gonna upload de source code?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lovethiscode** [comment]
rest api support 5.2
